field: be518519-84f1-484b-85d3-c9ad70561a68 # Home CTAs
fieldLayouts:
  641b924d-0a89-4b14-87f8-72df49e6491e:
    tabs:
      -
        elements:
          -
            fieldUid: 5e3f6df0-392b-45c2-9088-58547874aba3 # Home Link Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a5c8377e-c207-46a3-827a-a3246481f33e # Home Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5e3f6df0-392b-45c2-9088-58547874aba3: # Home Link Name
    columnSuffix: tcfijfma
    contentColumnType: text
    fieldGroup: null
    handle: homeLinkName
    instructions: ''
    name: 'Home Link Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a5c8377e-c207-46a3-827a-a3246481f33e: # Home Link
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: homeLink
    instructions: ''
    name: 'Home Link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: homeLinks
name: 'Home Links'
sortOrder: 1
