field: 6df5c000-efc5-4a29-a77e-c621461017e7 # Sizes
fieldLayouts:
  e7f4eb23-830b-48bf-8b54-2f6f4e3817b0:
    tabs:
      -
        elements:
          -
            fieldUid: 305d519a-5ada-4ae3-af49-990d7eb2216b # Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  305d519a-5ada-4ae3-af49-990d7eb2216b: # Size
    columnSuffix: nlincfnh
    contentColumnType: text
    fieldGroup: null
    handle: size
    instructions: ''
    name: Size
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: sizes
name: Sizes
sortOrder: 1
