columnSuffix: null
contentColumnType: string
fieldGroup: 57a48b92-00ac-4a12-b9d6-492526b3ed5f # Home
handle: mainImage
instructions: ''
name: 'Main Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:ad0e9212-0812-42db-a8c1-fcc684aa5682' # Uploads
  defaultUploadLocationSubpath: /main_image/
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:ad0e9212-0812-42db-a8c1-fcc684aa5682' # Uploads
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
