columnSuffix: null
contentColumnType: string
fieldGroup: 1f210362-85a9-4ba7-831c-bae7252dd65c # Product
handle: sizes
instructions: ''
name: Sizes
searchable: false
settings:
  contentTable: '{{%matrixcontent_sizes}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
