defaultPlacement: end
enableVersioning: true
handle: contactUs
name: 'Contact Us'
propagationMethod: all
siteSettings:
  1cf97504-5ced-4e1e-94c2-74f6bd2b9658: # Good Beers Inc
    enabledByDefault: true
    hasUrls: true
    template: contact-us/_entry
    uriFormat: contact-us
type: single
