defaultPlacement: end
enableVersioning: true
handle: stockist
name: Stockist
propagationMethod: all
siteSettings:
  1cf97504-5ced-4e1e-94c2-74f6bd2b9658: # Good Beers Inc
    enabledByDefault: true
    hasUrls: true
    template: stockist/_entry
    uriFormat: 'stockist/{slug}'
type: channel
